name="sarbaz"
name
type(name)
name[0]
name[4]
name[2]
name[-1]
name[-3]
name[:]
name[4:6]
name[1:4]
name[2:5]
name[::-1]
name[::2]
name[::4]
name[::5]
name[1::2]
dir(name)
name.upper()
name.title()
name.join('xz')
name.join('amban')
xz=1,2,3
xz=
type(xz)
xz
dir(xz)
xz[0]
xz[3]
xz[4]
xz[6]
xz[:2]
xz[::-3]
xz[2::4]
xz[::3]
xz[2:3]
xz.count()
xz.count(23)
xz.count(1)
xz.index(43)
xz.index('sarbaz')
xz.index(True)
[xz]
type(xz)
dir[xx]
xx=[xz]
xx=[,43,823-5j,"sarbaz",True,3+6,34.5]
xx
type(xx)
dir(xx)
xx[1]
xx[3]
list1=[43,823-5j,"sarbaz",True,3+6,34.5]
list1[2]
list1[4]
list1[:2]
list1[::3]
list1[2:3]
list1[::3]
list1[::-2]
list1[2::3]
list1[2][1:4]
list1[2][2:5]
list1.append(56)
list1
list1.insert(2,56)
list1
list7=[34,78-5j]
list7
list1.append(list7)
list1
#rangaa
student={1:'sarrbaz',2:'kattilasseri'}
student
type(student)
dir(student)
id(student)
student[0]
student[2]
student[1]
students={'name':'sarbaz','address':'kattilasseri','dob':'03-12-2005'}
students['name']
students['address']
students['dob']
students.keys()
students.values()
students.items()
students['age']
students['age']=19
students
students['name']='rangaa'
students
students.get('name')
students.update({'name':'ambaan','age':'21','address':'malappuram'})
students